#!/bin/bash
vol="$(mpc volume |cut -c 8-10)"
step=$((vol/10))

# fade down
for i in [1 2 3 4 5 6 7 8 9 10] ; do
        mpc volume -$step >/dev/null;
        sleep 0.07;
done

if [[ -n $1 ]]; then
	mpc play $1
else
	mpc next
fi

for i in [1 2 3 4 5 6 7 8 9 10] ; do
        mpc volume +$step >/dev/null;
        sleep 0.07;
done
